Flexible:
  allowFriendshipsAcrossPorts: false
  biologyInitializer:
    Multiple Species Abundance:
      addGarbageSpecies: true
      factories:
      - Boxcar Biology:
          LInfinity: '68.7'
          abundanceSimulator: null
          allometricAlpha: '0.0197'
          allometricBeta: '2.986'
          cmPerBin: 5.0
          cumulativePhi: '-1.0'
          diffuser: No Diffusion
          habitabilityAllocator:
            Equal Allocation:
              constantValue: '1.0'
          initialAbundanceAllocator:
            Single Peak Pyramid Allocator:
              maxSpread: 6
              peakBiomass: '1.0'
              peakX: '1.0'
              peakY: '1.0'
              smoothingValue: '0.7'
          initialBtOverK: '1.0'
          k: '0.23'
          lengthAtMaturity: '40.0'
          numberOfBins: 25
          recruitAllocator:
            Single Peak Pyramid Allocator:
              maxSpread: 6
              peakBiomass: '1.0'
              peakX: '1.0'
              peakY: '1.0'
              smoothingValue: '0.7'
          speciesName: Lethrinus laticaudis
          steepness: '0.8'
          virginRecruits: '-1.0'
          yearlyMortality: '0.339'
      - Boxcar Biology:
          LInfinity: '86.0'
          abundanceSimulator: null
          allometricAlpha: '0.00853'
          allometricBeta: '3.137'
          cmPerBin: 5.0
          cumulativePhi: '-1.0'
          diffuser: No Diffusion
          habitabilityAllocator:
            Equal Allocation:
              constantValue: '1.0'
          initialAbundanceAllocator:
            Single Peak Pyramid Allocator:
              maxSpread: 6
              peakBiomass: '1.0'
              peakX: '1.0'
              peakY: '1.0'
              smoothingValue: '0.7'
          initialBtOverK: '1.0'
          k: '0.4438437'
          lengthAtMaturity: '50.0'
          numberOfBins: 25
          recruitAllocator:
            Single Peak Pyramid Allocator:
              maxSpread: 6
              peakBiomass: '1.0'
              peakX: '1.0'
              peakY: '1.0'
              smoothingValue: '0.7'
          speciesName: Lutjanus malabaricus
          steepness: '0.8'
          virginRecruits: '-1.0'
          yearlyMortality: '0.3775984'
      - Boxcar Biology:
          LInfinity: '82.2'
          abundanceSimulator: null
          allometricAlpha: '0.0128'
          allometricBeta: '2.94'
          cmPerBin: 5.0
          cumulativePhi: '1.091855'
          diffuser: No Diffusion
          habitabilityAllocator:
            Equal Allocation:
              constantValue: '1.0'
          initialAbundanceAllocator:
            Single Peak Pyramid Allocator:
              maxSpread: 6
              peakBiomass: '1.0'
              peakX: '1.0'
              peakY: '1.0'
              smoothingValue: '0.7'
          initialBtOverK: '1.0'
          k: '0.198'
          lengthAtMaturity: '41.6'
          numberOfBins: 25
          recruitAllocator:
            Mirrored Peak Pyramid Allocator:
              maxSpread: 6
              noiseLevel: '0.1'
              peakBiomass: '1.0'
              peakX: '1.0'
              peakY: '1.0'
              smoothingValue: '0.7'
          speciesName: Atrobucca brevis
          steepness: '0.8'
          virginRecruits: '8133274.0'
          yearlyMortality: '0.353'
  cheaters: false
  exogenousCatches:
    Simple Exogenous Catches:
      yearlyBiomassToExtract:
        Lutjanus malabaricus: 421490
        Lethrinus laticaudis: 453317
  fisherDefinitions:
  - departingStrategy:
      Full-time Seasonal Retired Decorator:
        decorated:
          Max Hours Per Year:
            maxHoursOut: '4800.0'
        firstYearYouCanSwitch: '1.0'
        inertia: '1.0'
        maxHoursOutWhenSeasonal: '2352.0'
        minimumVariable: '0.0'
        probabilityStartingFullTime: '1.0'
        targetVariable: '138888.9'
        variableName: TRIP_PROFITS_PER_HOUR
    destinationStrategy:
      Imitator-Explorator:
        alwaysCopyBest: true
        automaticallyIgnoreAreasWhereFishNeverGrows: true
        automaticallyIgnoreMPAs: true
        backtracksOnBadExploration: true
        dropInUtilityNeededForUnfriend: '-1.0'
        ignoreEdgeDirection: true
        ignoreFailedTrips: false
        maxInitialDistance: -1.0
        objectiveFunction:
          Hourly Profit Objective:
            opportunityCosts: true
        probability:
          Fixed Probability:
            explorationProbability: '0.2'
            imitationProbability: '1.0'
        stepSize: '1.0'
    discardingStrategy: No Discarding
    fishingStrategy:
      Until Full With Day Limit:
        daysAtSea: '10.0'
    fuelTankSize: '9.9999999999E10'
    gear:
      Hour Delay Gear:
        delegate:
          Garbage Gear:
            delegate:
              Heterogeneous Selectivity Gear:
                gears:
                  Lethrinus laticaudis:
                    Simple Logistic Selectivity Gear:
                      averageCatchability: '9.288350700000002E-5'
                      litersOfGasConsumedPerHour: '0.0'
                      rounding: false
                      selexParameter1: '20.22'
                      selexParameter2: '0.5645'
                  Lutjanus malabaricus:
                    Simple Logistic Selectivity Gear:
                      averageCatchability: '0.95'
                      litersOfGasConsumedPerHour: '0.0'
                      rounding: false
                      selexParameter1: '21.923'
                      selexParameter2: '0.438'
                  Atrobucca brevis:
                    Simple Logistic Selectivity Gear:
                      averageCatchability: '9.288350700000002E-5'
                      litersOfGasConsumedPerHour: '0.0'
                      rounding: false
                      selexParameter1: '24'
                      selexParameter2: '0.6595'
                hourlyGasPriceOverride: '0.0'
            garbageSpeciesName: Others
            proportionSimulatedToGarbage: '0.3'
            rounding: false
        hoursItTake: '24.0'
    gearStrategy: Never Change Gear
    holdSize: '8000.0'
    hourlyVariableCost: uniform 40000.0 60000.0
    initialFishersPerPort:
      Port 0: 10
    literPerKilometer: '0.0'
    logbook: No Logbook
    regulation: Anarchy
    speedInKmh: '13.0'
    tags: red
    usePredictors: false
    weatherStrategy: Ignore Weather
  - departingStrategy:
      Full-time Seasonal Retired Decorator:
        decorated:
          Max Hours Per Year:
            maxHoursOut: '4800.0'
        firstYearYouCanSwitch: '1.0'
        inertia: '1.0'
        maxHoursOutWhenSeasonal: '2352.0'
        minimumVariable: '0.0'
        probabilityStartingFullTime: '1.0'
        targetVariable: '138888.9'
        variableName: TRIP_PROFITS_PER_HOUR
    destinationStrategy:
      Imitator-Explorator:
        alwaysCopyBest: true
        automaticallyIgnoreAreasWhereFishNeverGrows: true
        automaticallyIgnoreMPAs: true
        backtracksOnBadExploration: true
        dropInUtilityNeededForUnfriend: '-1.0'
        ignoreEdgeDirection: true
        ignoreFailedTrips: false
        maxInitialDistance: -1.0
        objectiveFunction:
          Hourly Profit Objective:
            opportunityCosts: true
        probability:
          Fixed Probability:
            explorationProbability: '0.2'
            imitationProbability: '1.0'
        stepSize: '1.0'
    discardingStrategy: No Discarding
    fishingStrategy:
      Until Full With Day Limit:
        daysAtSea: '10.0'
    fuelTankSize: '9.9999999999E10'
    gear:
      Hour Delay Gear:
        delegate:
          Garbage Gear:
            delegate:
              Heterogeneous Selectivity Gear:
                gears:
                  Lethrinus laticaudis:
                    Simple Logistic Selectivity Gear:
                      averageCatchability: '9.288350700000002E-5'
                      litersOfGasConsumedPerHour: '0.0'
                      rounding: false
                      selexParameter1: '20.22'
                      selexParameter2: '0.5645'
                  Lutjanus malabaricus:
                    Simple Logistic Selectivity Gear:
                      averageCatchability: '0.95'
                      litersOfGasConsumedPerHour: '0.0'
                      rounding: false
                      selexParameter1: '21.923'
                      selexParameter2: '0.438'
                  Atrobucca brevis:
                    Simple Logistic Selectivity Gear:
                      averageCatchability: '9.288350700000002E-5'
                      litersOfGasConsumedPerHour: '0.0'
                      rounding: false
                      selexParameter1: '24'
                      selexParameter2: '0.6595'
                hourlyGasPriceOverride: '0.0'
            garbageSpeciesName: Others
            proportionSimulatedToGarbage: '0.3'
            rounding: false
        hoursItTake: '24.0'
    gearStrategy: Never Change Gear
    holdSize: '8000.0'
    hourlyVariableCost: uniform 40000.0 60000.0
    initialFishersPerPort:
      Port 0: 10
    literPerKilometer: '0.0'
    logbook: No Logbook
    regulation: Anarchy
    speedInKmh: '13.0'
    tags: orange
    usePredictors: false
    weatherStrategy: Ignore Weather
  - departingStrategy:
      Full-time Seasonal Retired Decorator:
        decorated:
          Max Hours Per Year:
            maxHoursOut: '4800.0'
        firstYearYouCanSwitch: '1.0'
        inertia: '1.0'
        maxHoursOutWhenSeasonal: '2352.0'
        minimumVariable: '0.0'
        probabilityStartingFullTime: '1.0'
        targetVariable: '138888.9'
        variableName: TRIP_PROFITS_PER_HOUR
    destinationStrategy:
      Imitator-Explorator:
        alwaysCopyBest: true
        automaticallyIgnoreAreasWhereFishNeverGrows: true
        automaticallyIgnoreMPAs: true
        backtracksOnBadExploration: true
        dropInUtilityNeededForUnfriend: '-1.0'
        ignoreEdgeDirection: true
        ignoreFailedTrips: false
        maxInitialDistance: -1.0
        objectiveFunction:
          Hourly Profit Objective:
            opportunityCosts: true
        probability:
          Fixed Probability:
            explorationProbability: '0.2'
            imitationProbability: '1.0'
        stepSize: '1.0'
    discardingStrategy: No Discarding
    fishingStrategy:
      Until Full With Day Limit:
        daysAtSea: '10.0'
    fuelTankSize: '9.9999999999E10'
    gear:
      Hour Delay Gear:
        delegate:
          Garbage Gear:
            delegate:
              Heterogeneous Selectivity Gear:
                gears:
                  Lethrinus laticaudis:
                    Simple Dome Shaped Selectivity Gear:
                      averageCatchability: '0.0'
                      lengthFullSelectivity: '30.0'
                      litersOfGasConsumedPerHour: '0.0'
                      rounding: false
                      slopeLeft: '5.0'
                      slopeRight: '10.0'
                  Lutjanus malabaricus:
                    Simple Dome Shaped Selectivity Gear:
                      averageCatchability: '0.0'
                      lengthFullSelectivity: '30.0'
                      litersOfGasConsumedPerHour: '0.0'
                      rounding: false
                      slopeLeft: '5.0'
                      slopeRight: '10.0'
                  Atrobucca brevis:
                    Simple Logistic Selectivity Gear:
                      averageCatchability: '0'
                      litersOfGasConsumedPerHour: '0.0'
                      rounding: false
                      selexParameter1: '9999'
                      selexParameter2: '1'
                hourlyGasPriceOverride: '0.0'
            garbageSpeciesName: Others
            proportionSimulatedToGarbage: '0.3'
            rounding: false
        hoursItTake: '24.0'
    gearStrategy: Never Change Gear
    holdSize: '8000.0'
    hourlyVariableCost: uniform 40000.0 60000.0
    initialFishersPerPort:
      Port 0: 10
    literPerKilometer: '0.0'
    logbook: No Logbook
    regulation: Anarchy
    speedInKmh: '13.0'
    tags: black,gillnet
    usePredictors: false
    weatherStrategy: Ignore Weather
  gasPricePerLiter: '0.0'
  habitatInitializer: All Sand
  mapInitializer:
    Map with far-off ports:
      delegate:
        Simple Map:
          cellSizeInKilometers: '100.0'
          coastalRoughness: '0.0'
          depthSmoothing: '1000000.0'
          height: '5.0'
          maxInitialDepth: '5000.0'
          maxLandWidth: '1.0'
          minInitialDepth: '5000.0'
          width: '6.0'
      farOffPorts:
      - distanceFromExitInKm: 1500.0
        exitGridX: 0
        exitGridY: 5
        gasPriceAtPort: 0.0
        marketMaker:
          Fixed Price Market:
            marketPrice: '100.0'
        portName: Far-off
  mapMakerDedicatedRandomSeed: 0
  market:
    Fixed Price Market:
      marketPrice: '40000.0'
  networkBuilder:
    Equal Out Degree:
      allowMutualFriendships: true
      degree: '2.0'
      equalOutDegree: true
      predicates: [
        ]
  plugins:
  - Fish Entry By Profit:
      costsFinalColumnName: Average Variable Costs of population0
      fixedCostsToCover: '0.0'
      maxEntrantsPerYear: '20.0'
      populationName: population0
      profitDataColumnName: Average Cash-Flow of population0
      profitRatioToEntrantsMultiplier: '10.0'
  - Fish Entry By Profit:
      costsFinalColumnName: Average Variable Costs of population1
      fixedCostsToCover: '0.0'
      maxEntrantsPerYear: '20.0'
      populationName: population1
      profitDataColumnName: Average Cash-Flow of population1
      profitRatioToEntrantsMultiplier: '10.0'
  - Fish Entry By Profit:
      costsFinalColumnName: Average Variable Costs of population2
      fixedCostsToCover: '0.0'
      maxEntrantsPerYear: '20.0'
      populationName: population2
      profitDataColumnName: Average Cash-Flow of population2
      profitRatioToEntrantsMultiplier: '10.0'
  - SPR Agent:
      assumedKParameter: '0.322'
      assumedLengthAtMaturity: '29.0'
      assumedLengthBinCm: '5.0'
      assumedLinf: '59.0'
      assumedNaturalMortality: '0.495'
      assumedVarA: '0.0197'
      assumedVarB: '2.99'
      probabilityOfSamplingEachBoat: '1.0'
      simulatedMaxAge: '100.0'
      simulatedVirginRecruits: '1000.0'
      speciesName: Lethrinus laticaudis
      surveyTag: spr_agent1
  - SPR Agent:
      assumedKParameter: '0.4438437'
      assumedLengthAtMaturity: '50.0'
      assumedLengthBinCm: '5.0'
      assumedLinf: '86.0'
      assumedNaturalMortality: '0.3775984'
      assumedVarA: '0.00853'
      assumedVarB: '3.137'
      probabilityOfSamplingEachBoat: '1.0'
      simulatedMaxAge: '100.0'
      simulatedVirginRecruits: '1000.0'
      speciesName: Lutjanus malabaricus
      surveyTag: spr_agent2
  - SPR Agent:
      assumedKParameter: '0.291'
      assumedLengthAtMaturity: '34.0'
      assumedLengthBinCm: '5.0'
      assumedLinf: '68.0'
      assumedNaturalMortality: '0.447'
      assumedVarA: '0.0128'
      assumedVarB: '2.94'
      probabilityOfSamplingEachBoat: '1.0'
      simulatedMaxAge: '100.0'
      simulatedVirginRecruits: '1000.0'
      speciesName: Atrobucca brevis
      surveyTag: spr_agent3
  portInitializer:
    One Port:
      portPositionX: '5.0'
      portPositionY: '0.0'
  portSwitching: false
  tagsToTrackSeparately: ''
  weatherInitializer:
    Constant Weather:
      temperature: '30.0'
      windOrientation: '0.0'
      windSpeed: '0.0'
